### ISSUE TITLE
Electron Security Warning (Insecure Resources)

### ISSUE THREAD

**Issue by sdcdsvsdv423** [nuxt/electron#21]
Hello, is there any way to fix this warning?
<img width="602" alt="2018-05-12 11 44 55" src="https://user-images.githubusercontent.com/5320711/39954267-337a96e2-55da-11e8-82c2-bfb222507a52.png">

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/electron-template/issues/c17">#c17</a>)</em></sub></div>

**Comment by esindger** [comment]
Why the issue has been closed?

**Comment by HoraceKeung** [comment]
The issue is now here: https://nuxtjs.cmty.io/nuxt-community/electron-template/issues/c17
